// <auto-generated />
using System;
using GrandPeltekHotel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrandPeltekHotel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200512145506_AddedRoomsAndCategories")]
    partial class AddedRoomsAndCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrandPeltekHotel.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bedroom with a queen-sized bed, living room with a couch, table and fully equpped kitchen",
                            Name = "Apartments"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bedroom with a queen-sized bed and couch",
                            Name = "Double-bed rooms"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bedroom with two separate medium-sized beds for minimum intimacy",
                            Name = "Rooms with two separate beds"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bedroom with three separate medium-sized beds",
                            Name = "Rooms with three separate beds"
                        });
                });

            modelBuilder.Entity("GrandPeltekHotel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberofBookedRooms")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("GrandPeltekHotel.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("GrandPeltekHotel.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<bool>("SignedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
